import type { LeadResult } from "./types";

export const DEMO_LEADS: LeadResult[] = [
  {
    id: "demo-1",
    company_name: "Skyline Office Solutions",
    contact_name: "Michael Torres",
    email: "mtorres@skylineoffices.com",
    phone: "(312) 555-0101",
    website: "https://skylineoffices.com",
    industry: "Property Management",
    city: "Chicago",
    state: "IL",
    zip: "60601",
    business_size: "50-200",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-2",
    company_name: "Greenway Logistics",
    contact_name: "Sarah Chen",
    email: "schen@greenwaylog.com",
    phone: "(415) 555-0202",
    website: "https://greenwaylog.com",
    industry: "Logistics",
    city: "San Francisco",
    state: "CA",
    zip: "94105",
    business_size: "50-200",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-3",
    company_name: "Atlas Construction Group",
    contact_name: "David Martinez",
    email: "dmartinez@atlasconst.com",
    phone: "(512) 555-0303",
    website: "https://atlasconst.com",
    industry: "Construction",
    city: "Austin",
    state: "TX",
    zip: "73301",
    business_size: "50-200",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-4",
    company_name: "BluePeak Insurance",
    contact_name: "Jennifer Adams",
    email: "jadams@bluepeakins.com",
    phone: "(303) 555-0404",
    website: "https://bluepeakins.com",
    industry: "Insurance",
    city: "Denver",
    state: "CO",
    zip: "80202",
    business_size: "5-50",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-5",
    company_name: "TechBridge Staffing",
    contact_name: "Robert Kim",
    email: "rkim@techbridgestaff.com",
    phone: "(206) 555-0505",
    website: "https://techbridgestaff.com",
    industry: "Recruiting",
    city: "Seattle",
    state: "WA",
    zip: "98101",
    business_size: "5-50",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-6",
    company_name: "Prime Commercial Cleaning",
    contact_name: "Lisa Thompson",
    email: "lthompson@primeclean.com",
    phone: "(214) 555-0606",
    website: "https://primeclean.com",
    industry: "Commercial Cleaning",
    city: "Dallas",
    state: "TX",
    zip: "75201",
    business_size: "5-50",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-7",
    company_name: "Evergreen Landscaping Co",
    contact_name: "James Wilson",
    email: "jwilson@evergreenland.com",
    phone: "(404) 555-0707",
    website: "https://evergreenland.com",
    industry: "Commercial Cleaning",
    city: "Atlanta",
    state: "GA",
    zip: "30303",
    business_size: "5-50",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-8",
    company_name: "Metro Freight Solutions",
    contact_name: "Amanda Rivera",
    email: "arivera@metrofreight.com",
    phone: "(213) 555-0808",
    website: "https://metrofreight.com",
    industry: "Logistics",
    city: "Los Angeles",
    state: "CA",
    zip: "90001",
    business_size: "50-200",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-9",
    company_name: "Peak Roofing & Exteriors",
    contact_name: "Chris Baker",
    email: "cbaker@peakroofing.com",
    phone: "(602) 555-0909",
    website: "https://peakroofing.com",
    industry: "Construction",
    city: "Phoenix",
    state: "AZ",
    zip: "85001",
    business_size: "5-50",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-10",
    company_name: "MediaSpark Agency",
    contact_name: "Nina Patel",
    email: "npatel@mediaspark.co",
    phone: "(917) 555-1010",
    website: "https://mediaspark.co",
    industry: "Marketing",
    city: "New York",
    state: "NY",
    zip: "10001",
    business_size: "5-50",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-11",
    company_name: "Titan Industrial Supply",
    contact_name: "Frank Russo",
    email: "frusso@titanindustrial.com",
    phone: "(713) 555-1111",
    website: "https://titanindustrial.com",
    industry: "Logistics",
    city: "Houston",
    state: "TX",
    zip: "77001",
    business_size: "50-200",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-12",
    company_name: "HarborView Realty",
    contact_name: "Diana Foster",
    email: "dfoster@harborview.com",
    phone: "(617) 555-1212",
    website: "https://harborview.com",
    industry: "Real Estate",
    city: "Boston",
    state: "MA",
    zip: "02101",
    business_size: "5-50",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-13",
    company_name: "SunState HVAC Services",
    contact_name: "Marcus Johnson",
    email: "mjohnson@sunstatehvac.com",
    phone: "(305) 555-1313",
    website: "https://sunstatehvac.com",
    industry: "Construction",
    city: "Miami",
    state: "FL",
    zip: "33101",
    business_size: "5-50",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-14",
    company_name: "NorthStar Security",
    contact_name: "Rachel Greene",
    email: "rgreene@northstarsec.com",
    phone: "(612) 555-1414",
    website: "https://northstarsec.com",
    industry: "Property Management",
    city: "Minneapolis",
    state: "MN",
    zip: "55401",
    business_size: "50-200",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-15",
    company_name: "Capital Junk Removal",
    contact_name: "Tom Fletcher",
    email: "tfletcher@capitaljunk.com",
    phone: "(202) 555-1515",
    website: "https://capitaljunk.com",
    industry: "Commercial Cleaning",
    city: "Washington",
    state: "DC",
    zip: "20001",
    business_size: "1-5",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-16",
    company_name: "Apex Electric Services",
    contact_name: "Kevin Chang",
    email: "kchang@apexelect.com",
    phone: "(702) 555-1616",
    website: "https://apexelect.com",
    industry: "Construction",
    city: "Las Vegas",
    state: "NV",
    zip: "89101",
    business_size: "5-50",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-17",
    company_name: "River City Plumbing",
    contact_name: "Patricia Owens",
    email: "powens@rivercityplumb.com",
    phone: "(804) 555-1717",
    website: "https://rivercityplumb.com",
    industry: "Construction",
    city: "Richmond",
    state: "VA",
    zip: "23218",
    business_size: "5-50",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-18",
    company_name: "BrightMind Tutoring",
    contact_name: "Steven Diaz",
    email: "sdiaz@brightmindtutor.com",
    phone: "(503) 555-1818",
    website: "https://brightmindtutor.com",
    industry: "Marketing",
    city: "Portland",
    state: "OR",
    zip: "97201",
    business_size: "1-5",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-19",
    company_name: "Coastal Pressure Washing",
    contact_name: "Maria Santos",
    email: "msantos@coastalwash.com",
    phone: "(843) 555-1919",
    website: "https://coastalwash.com",
    industry: "Commercial Cleaning",
    city: "Charleston",
    state: "SC",
    zip: "29401",
    business_size: "1-5",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
  {
    id: "demo-20",
    company_name: "DataVault IT Solutions",
    contact_name: "Andrew Park",
    email: "apark@datavaultit.com",
    phone: "(408) 555-2020",
    website: "https://datavaultit.com",
    industry: "Marketing",
    city: "San Jose",
    state: "CA",
    zip: "95101",
    business_size: "50-200",
    email_status: "valid",
    source: "demo",
    source_provider: "demo",
  },
];
