import type { LeadResult } from "./types";

export const DEMO_LEADS: LeadResult[] = [
  // ── Roofing (7) ──────────────────────────────────────────────
  {
    id: "demo-1", company_name: "Desert Sky Roofing", contact_name: "Jake Moreno",
    email: "jmoreno@desertskyroofing.com", phone: "(602) 555-1001",
    website: "https://desertskyroofing.com", industry: "Roofing",
    city: "Phoenix", state: "AZ", zip: "85001", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-2", company_name: "Coastal Shield Roofing", contact_name: "Luis Herrera",
    email: "lherrera@coastalshield.com", phone: "(305) 555-1002",
    website: "https://coastalshieldroofing.com", industry: "Roofing",
    city: "Miami", state: "FL", zip: "33101", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-3", company_name: "Peach State Roofing", contact_name: "Tyrone Brooks",
    email: "tbrooks@peachstateroof.com", phone: "(404) 555-1003",
    website: "https://peachstateroof.com", industry: "Roofing",
    city: "Atlanta", state: "GA", zip: "30303", business_size: "50-200",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-4", company_name: "Gulf Coast Roofing Pros", contact_name: "Brenda Shaw",
    email: "bshaw@gulfcoastroof.com", phone: "(713) 555-1004",
    website: "https://gulfcoastroof.com", industry: "Roofing",
    city: "Houston", state: "TX", zip: "77001", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-5", company_name: "Queen City Roofing", contact_name: "Derek Mills",
    email: "dmills@queencityroof.com", phone: "(704) 555-1005",
    website: "https://queencityroof.com", industry: "Roofing",
    city: "Charlotte", state: "NC", zip: "28202", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-6", company_name: "Mile High Roofing Co", contact_name: "Carla Nguyen",
    email: "cnguyen@milehighroof.com", phone: "(303) 555-1006",
    website: "https://milehighroof.com", industry: "Roofing",
    city: "Denver", state: "CO", zip: "80202", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-7", company_name: "Bay Area Roofing FL", contact_name: "Marco Estrada",
    email: "mestrada@bayarearoofing.com", phone: "(813) 555-1007",
    website: "https://bayarearoofingfl.com", industry: "Roofing",
    city: "Tampa", state: "FL", zip: "33601", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },

  // ── Pressure Washing (6) ─────────────────────────────────────
  {
    id: "demo-8", company_name: "Sunshine Pressure Wash", contact_name: "Rita Cobb",
    email: "rcobb@sunshinewash.com", phone: "(813) 555-2001",
    website: "https://sunshinewash.com", industry: "Pressure Washing",
    city: "Tampa", state: "FL", zip: "33602", business_size: "1-5",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-9", company_name: "Central Florida Wash", contact_name: "Evan Short",
    email: "eshort@centralflwash.com", phone: "(407) 555-2002",
    website: "https://centralflwash.com", industry: "Pressure Washing",
    city: "Orlando", state: "FL", zip: "32801", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-10", company_name: "Music City Pressure Wash", contact_name: "Tanya Wyatt",
    email: "twyatt@musiccitywash.com", phone: "(615) 555-2003",
    website: "https://musiccitywash.com", industry: "Pressure Washing",
    city: "Nashville", state: "TN", zip: "37201", business_size: "1-5",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-11", company_name: "Cascade Clean Exteriors", contact_name: "Gina Fowler",
    email: "gfowler@cascadeclean.com", phone: "(503) 555-2004",
    website: "https://cascadeclean.com", industry: "Pressure Washing",
    city: "Portland", state: "OR", zip: "97201", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-12", company_name: "Pacific Breeze Wash", contact_name: "Ronnie Vega",
    email: "rvega@pacificbreezewash.com", phone: "(619) 555-2005",
    website: "https://pacificbreezewash.com", industry: "Pressure Washing",
    city: "San Diego", state: "CA", zip: "92101", business_size: "1-5",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-13", company_name: "Piedmont Pressure Pros", contact_name: "Ian Drake",
    email: "idrake@piedmontpros.com", phone: "(678) 555-2006",
    website: "https://piedmontpros.com", industry: "Pressure Washing",
    city: "Atlanta", state: "GA", zip: "30304", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },

  // ── Junk Removal (6) ─────────────────────────────────────────
  {
    id: "demo-14", company_name: "Valley Junk Haulers", contact_name: "Sonia Ramos",
    email: "sramos@valleyjunk.com", phone: "(480) 555-3001",
    website: "https://valleyjunk.com", industry: "Junk Removal",
    city: "Phoenix", state: "AZ", zip: "85002", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-15", company_name: "Desert Oasis Junk", contact_name: "Mitch Harper",
    email: "mharper@desertoasisjunk.com", phone: "(702) 555-3002",
    website: "https://desertoasisjunk.com", industry: "Junk Removal",
    city: "Las Vegas", state: "NV", zip: "89101", business_size: "1-5",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-16", company_name: "Lone Star Hauling", contact_name: "Clay Jennings",
    email: "cjennings@lonestarhaul.com", phone: "(512) 555-3003",
    website: "https://lonestarhaul.com", industry: "Junk Removal",
    city: "Austin", state: "TX", zip: "73301", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-17", company_name: "Buckeye Junk Removal", contact_name: "Nora Fields",
    email: "nfields@buckeyejunk.com", phone: "(614) 555-3004",
    website: "https://buckeyejunk.com", industry: "Junk Removal",
    city: "Columbus", state: "OH", zip: "43215", business_size: "1-5",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-18", company_name: "River City Junk", contact_name: "Lance Pruitt",
    email: "lpruitt@rivercityjunk.com", phone: "(916) 555-3005",
    website: "https://rivercityjunk.com", industry: "Junk Removal",
    city: "Sacramento", state: "CA", zip: "95814", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-19", company_name: "Front Range Haulers", contact_name: "Dina Sharpe",
    email: "dsharpe@frontrangehaul.com", phone: "(720) 555-3006",
    website: "https://frontrangehaul.com", industry: "Junk Removal",
    city: "Denver", state: "CO", zip: "80203", business_size: "1-5",
    email_status: "valid", source: "demo", source_provider: "demo",
  },

  // ── Freight / Logistics (6) ──────────────────────────────────
  {
    id: "demo-20", company_name: "Delta Freight Solutions", contact_name: "Warren Nash",
    email: "wnash@deltafreight.com", phone: "(901) 555-4001",
    website: "https://deltafreightsol.com", industry: "Freight/Logistics",
    city: "Memphis", state: "TN", zip: "38103", business_size: "50-200",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-21", company_name: "Derby City Logistics", contact_name: "Tricia Hines",
    email: "thines@derbycitylog.com", phone: "(502) 555-4002",
    website: "https://derbycitylogistics.com", industry: "Freight/Logistics",
    city: "Louisville", state: "KY", zip: "40202", business_size: "50-200",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-22", company_name: "Windy City Freight", contact_name: "Vince McNeil",
    email: "vmcneil@windycityfreight.com", phone: "(312) 555-4003",
    website: "https://windycityfreight.com", industry: "Freight/Logistics",
    city: "Chicago", state: "IL", zip: "60601", business_size: "50-200",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-23", company_name: "Gateway Logistics Group", contact_name: "Esther Huang",
    email: "ehuang@gatewaylog.com", phone: "(973) 555-4004",
    website: "https://gatewayloggroup.com", industry: "Freight/Logistics",
    city: "Newark", state: "NJ", zip: "07101", business_size: "50-200",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-24", company_name: "Bay Bridge Freight", contact_name: "Sharon Decker",
    email: "sdecker@baybridgefreight.com", phone: "(510) 555-4005",
    website: "https://baybridgefreight.com", industry: "Freight/Logistics",
    city: "Oakland", state: "CA", zip: "94601", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-25", company_name: "Lone Star Logistics TX", contact_name: "Heath Cantrell",
    email: "hcantrell@lonestarlogtx.com", phone: "(214) 555-4006",
    website: "https://lonestarlogtx.com", industry: "Freight/Logistics",
    city: "Dallas", state: "TX", zip: "75201", business_size: "50-200",
    email_status: "valid", source: "demo", source_provider: "demo",
  },

  // ── Commercial Cleaning (6) ──────────────────────────────────
  {
    id: "demo-26", company_name: "Emerald City Clean", contact_name: "June Holloway",
    email: "jholloway@emeraldcityclean.com", phone: "(206) 555-5001",
    website: "https://emeraldcityclean.com", industry: "Commercial Cleaning",
    city: "Seattle", state: "WA", zip: "98101", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-27", company_name: "North Star Commercial Clean", contact_name: "Leonard Fry",
    email: "lfry@northstarclean.com", phone: "(612) 555-5002",
    website: "https://northstarclean.com", industry: "Commercial Cleaning",
    city: "Minneapolis", state: "MN", zip: "55401", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-28", company_name: "Beacon Hill Cleaners", contact_name: "Kendra Blair",
    email: "kblair@beaconhillclean.com", phone: "(617) 555-5003",
    website: "https://beaconhillclean.com", industry: "Commercial Cleaning",
    city: "Boston", state: "MA", zip: "02101", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-29", company_name: "Wasatch Clean Co", contact_name: "Grant Webber",
    email: "gwebber@wasatchclean.com", phone: "(801) 555-5004",
    website: "https://wasatchclean.com", industry: "Commercial Cleaning",
    city: "Salt Lake City", state: "UT", zip: "84101", business_size: "1-5",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-30", company_name: "Triangle Commercial Clean", contact_name: "Holly Dunlap",
    email: "hdunlap@triangleclean.com", phone: "(919) 555-5005",
    website: "https://triangleclean.com", industry: "Commercial Cleaning",
    city: "Raleigh", state: "NC", zip: "27601", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-31", company_name: "Gateway Commercial Clean", contact_name: "Ross Golden",
    email: "rgolden@gatewayclean.com", phone: "(314) 555-5006",
    website: "https://gatewayclean.com", industry: "Commercial Cleaning",
    city: "St. Louis", state: "MO", zip: "63101", business_size: "1-5",
    email_status: "valid", source: "demo", source_provider: "demo",
  },

  // ── Construction (5) ─────────────────────────────────────────
  {
    id: "demo-32", company_name: "Atlas Construction Group", contact_name: "David Martinez",
    email: "dmartinez@atlasconst.com", phone: "(512) 555-6001",
    website: "https://atlasconst.com", industry: "Construction",
    city: "Austin", state: "TX", zip: "73301", business_size: "50-200",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-33", company_name: "SunState HVAC Services", contact_name: "Marcus Johnson",
    email: "mjohnson@sunstatehvac.com", phone: "(305) 555-6002",
    website: "https://sunstatehvac.com", industry: "Construction",
    city: "Miami", state: "FL", zip: "33101", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-34", company_name: "Apex Electric Services", contact_name: "Kevin Chang",
    email: "kchang@apexelect.com", phone: "(702) 555-6003",
    website: "https://apexelect.com", industry: "Construction",
    city: "Las Vegas", state: "NV", zip: "89101", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-35", company_name: "River City Plumbing", contact_name: "Patricia Owens",
    email: "powens@rivercityplumb.com", phone: "(804) 555-6004",
    website: "https://rivercityplumb.com", industry: "Construction",
    city: "Richmond", state: "VA", zip: "23218", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-36", company_name: "Great Lakes Builders", contact_name: "Andre Stanton",
    email: "astanton@greatlakesbuild.com", phone: "(313) 555-6005",
    website: "https://greatlakesbuild.com", industry: "Construction",
    city: "Detroit", state: "MI", zip: "48226", business_size: "50-200",
    email_status: "valid", source: "demo", source_provider: "demo",
  },

  // ── Real Estate (5) ──────────────────────────────────────────
  {
    id: "demo-37", company_name: "Ocean Drive Realty", contact_name: "Yvonne Castor",
    email: "ycastor@oceandriverealty.com", phone: "(786) 555-7001",
    website: "https://oceandriverealty.com", industry: "Real Estate",
    city: "Miami", state: "FL", zip: "33139", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-38", company_name: "Cactus Valley Properties", contact_name: "Simon Brandt",
    email: "sbrandt@cactusvalley.com", phone: "(480) 555-7002",
    website: "https://cactusvalleyprop.com", industry: "Real Estate",
    city: "Phoenix", state: "AZ", zip: "85003", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-39", company_name: "Strip Real Estate Group", contact_name: "Darlene Riggs",
    email: "driggs@striprealestate.com", phone: "(702) 555-7003",
    website: "https://striprealestate.com", industry: "Real Estate",
    city: "Las Vegas", state: "NV", zip: "89102", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-40", company_name: "HarborView Realty", contact_name: "Diana Foster",
    email: "dfoster@harborview.com", phone: "(617) 555-7004",
    website: "https://harborviewrealty.com", industry: "Real Estate",
    city: "Boston", state: "MA", zip: "02101", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-41", company_name: "Bay City Properties", contact_name: "Oscar Medina",
    email: "omedina@baycityprops.com", phone: "(415) 555-7005",
    website: "https://baycityprops.com", industry: "Real Estate",
    city: "San Francisco", state: "CA", zip: "94102", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },

  // ── Insurance (4) ────────────────────────────────────────────
  {
    id: "demo-42", company_name: "BluePeak Insurance", contact_name: "Jennifer Adams",
    email: "jadams@bluepeakins.com", phone: "(303) 555-8001",
    website: "https://bluepeakins.com", industry: "Insurance",
    city: "Denver", state: "CO", zip: "80202", business_size: "5-50",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-43", company_name: "Charter Oak Insurance", contact_name: "Lydia Cross",
    email: "lcross@charteroakins.com", phone: "(860) 555-8002",
    website: "https://charteroakins.com", industry: "Insurance",
    city: "Hartford", state: "CT", zip: "06103", business_size: "50-200",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-44", company_name: "Prairie State Mutual", contact_name: "Greg Whalen",
    email: "gwhalen@prairiestatemutual.com", phone: "(515) 555-8003",
    website: "https://prairiestatemutual.com", industry: "Insurance",
    city: "Des Moines", state: "IA", zip: "50309", business_size: "50-200",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
  {
    id: "demo-45", company_name: "Heartland Insurance Co", contact_name: "Faith Noble",
    email: "fnoble@heartlandinsco.com", phone: "(402) 555-8004",
    website: "https://heartlandinsco.com", industry: "Insurance",
    city: "Omaha", state: "NE", zip: "68102", business_size: "50-200",
    email_status: "valid", source: "demo", source_provider: "demo",
  },
];
